### ISSUE TITLE
"Authentication method blocked" error while signing transaction

### ISSUE THREAD

**Issue by mossid** [cosmos/ledger-cosmos-obsolete#126]
```
confirm transaction before signing and broadcasting [Y/n]: y
ERROR: [APDU_CODE_OUTPUT_BUFFER_TOO_SMALL] Authentication method blocked
```

Enviorment:
* Device: Ledger Nano S
* Firmware version: 1.4.2
* App Version: 1.0.0
* Ledger Live Version: 1.6.0

**Comment by jleni** [comment]
Thanks!
This issue has been fixed in v1.0.1 and upwards.
Could you please try upgrading?

**Comment by jleni** [comment]
if it does not work please reopen this issue

**Comment by mossid** [comment]
Thanks, however, ledger live is only showing Cosmos app v1.0.0, it is built from the source with `yarn`. Running in developer mode.

**Comment by jleni** [comment]
This is probably because v1.0.1 and upwards require your ledger to upgrade to 1.5.5

There are known vulnerabilities in Ledger firmware 1.4.2, please upgrade to 1.5.5

Once you upgrade, you should see the latest Cosmos app, i.e. v1.1.1
