### ISSUE TITLE
Reject button is unresponsive

### ISSUE THREAD

**Issue by jbibla** [cosmos/ledger-cosmos-obsolete#134]
hello @jleni ! 

thank you for all your work on this ledger app! 

i tried to reject a transaction on my ledger nano s but the reject button seems unresponsive. seems like nothing happens at all.

ledger nano s firmware: v1.5.5
cosmos-ledger app: v1.1.1

**Comment by jleni** [comment]
I cannot reproduce this problem. I will contact you directly too discuss repro steps.

**Comment by jbibla** [comment]
i was not able to reproduce this again either. will close for now.
