### ISSUE TITLE
Increase amount of tokens the JSON tokenizer can handle

### ISSUE THREAD

**Issue by awrelll** [cosmos/ledger-cosmos-obsolete#143]
I get this error `ERROR: NOMEM: JSON string contains too many tokens
` while using the CLI to do  `gaiacli tx distr withdraw-all-rewards`. 
Using LedgerNanoS with Cosmos app 1.5 and gaiacli `0.34.3-120-gf8fd50a0`

**Comment by jleni** [comment]
https://github.com/LedgerHQ/ledger-app-cosmos/pull/7
Merged + Released
