### ISSUE TITLE
Regression between 0.34.3 and 0.34.4 for displaying keys from gaiacli

### ISSUE THREAD

**Issue by zmanian** [cosmos/ledger-cosmos-obsolete#144]
Displaying my key on the device with gaiacli works on `v0.34.3` but not on `v0.34.4`

```
gaiacli version
0.34.3-107-g829ce17d0
```

```
gaiacli keys show -d zaki-ledger
NAME:	TYPE:	ADDRESS:					PUBKEY:
zaki-ledger	ledger         xxx                                         xxx
```
Keys is displayed on the ledger

```
gaiacli version
0.34.4
```

```
NAME:	TYPE:	ADDRESS:					PUBKEY:
zaki-ledger	ledger  xxx   xxx
ERROR: [APDU_CODE_INS_NOT_SUPPORTED] Instruction code not supported or invalid
```
Key is not displayed on the ledger.

**Comment by zmanian** [comment]
Okay the problem is I can't figure out how to reproducibly build the working version.

I think the issue is in the version of  `leger-cosmos-go` but versions like `v0.9.10` don't build for dependency management issues.

**Comment by jleni** [comment]
@zmanian I have just tried it out but I could not reproduce the problem.
What is your:
- Device Type?  Nano X or Nano S
- Cosmos App Version?

**Comment by zmanian** [comment]
Nano S

Cosmos App V1.5 

Mac 0S

**Comment by jleni** [comment]
Moving the issue to gaia
https://github.com/cosmos/gaia/issues/13
