### ISSUE TITLE
[Ledger nano X] ERROR:  ledger nano S: no ledger connected

### ISSUE THREAD

**Issue by TheBonseung** [cosmos/ledger-cosmos-obsolete#147]
I got this error. (I think it is the same with https://forum.cosmos.network/t/attention-ledger-cosmos-app-users/2083/5 )

$ gaiacli keys add <keyname> --ledger
ERROR: ledger nano S: no ledger connected

Environment 
Device : Ledger Nano X (Ledger Live 1.8.1, Cosmos app 1.5)
OS : Ubuntu 18.04 (x64)
Gaiacli version : 0.34.2

**Comment by jleni** [comment]
Thanks @TheBonseung for the report.

Nano X support is included in Gaia v0.34.5
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.34.5
