### ISSUE TITLE
Roadmap for production app

### ISSUE THREAD

**Issue by zramsay** [cosmos/ledger-cosmos-obsolete#15]
from: https://github.com/cosmos/cosmos-ledger/issues/3

close if irrelevant

**Comment by kidinamoto01** [comment]
when will ledger for cosmos be available?

**Comment by zramsay** [comment]
see https://github.com/cosmos/cosmos-sdk/issues/910

**Comment by jleni** [comment]
I think this could be close. Could you confirm? @cwgoes @zramsay

**Comment by cwgoes** [comment]
Haha, I'd never actually read the original issue, but we ended up implementing all of the listed features. This can be closed (I don't have permissions on this repo, you'll have to do it).
