### ISSUE TITLE
Cosmos app crashing

### ISSUE THREAD

**Issue by thimomerke** [cosmos/ledger-cosmos-obsolete#153]
I've been trying to sign a transaction (delegation/send ATOMs) with different web wallets/browsers/PCs. In every case, when pressing 'Sign transaction', Windows Security first shows an error, and when pressing again the Ledger simply crashes. (Ledger on 1.5.5, Cosmos 1.5.3)

**Comment by jleni** [comment]
Very likely related to https://github.com/luniehq/lunie/issues/2754
