### ISSUE TITLE
Unable to install submodules

### ISSUE THREAD

**Issue by shikharfb** [cosmos/ledger-cosmos-obsolete#154]
Issue while updating `submodules` 

Command : `git submodule update --init --recursive`

Output:

```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:tendermint/ledger-validator-app.git' into submodule path '/home/shikhar/go/src/github.com/ledger-cosmos/src/ledger-val' failed
Failed to clone 'src/ledger-val' a second time, aborting
Cloning into '/home/shikhar/go/src/github.com/ledger-cosmos/deps/nanos-secure-sdk'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

```

**Comment by jleni** [comment]
The submodules seen to be using SSH instead of HTTP.

I will update that to avoid these issues. In the meantime, a workaround is to connect to github with SSH credentials.

https://help.github.com/en/enterprise/2.16/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by shikharfb** [comment]
Cool, thanks.
