### ISSUE TITLE
Ledger-Cosmo Generic C++ Code make Error

### ISSUE THREAD

**Issue by saadbutt** [cosmos/ledger-cosmos-obsolete#155]
[ 26%] Built target user_json_parser
make[3]: *** No rule to make target 'build_cosmos'.  Stop.
CMakeFiles/ledger_user_app.dir/build.make:57: recipe for target 'CMakeFiles/ledger_user_app' failed
make[2]: *** [CMakeFiles/ledger_user_app] Error 2
CMakeFiles/Makefile2:144: recipe for target 'CMakeFiles/ledger_user_app.dir/all' failed
make[1]: *** [CMakeFiles/ledger_user_app.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jleni** [comment]
I will investigate but in the meantime check at CircleCI config.

https://github.com/cosmos/ledger-cosmos/blob/8c389e18c92ba9bd6ad41780a938f07b0234e8fd/.circleci/config.yml#L12

If you run something like `cmake -DDISABLE_DOCKER_BUILDS=ON . && make` it will compile local code but it will not try to crosscompile the apps. Typically this is more efficient too.

**Comment by saadbutt** [comment]
Working on local. Thanks.

> I will investigate but in the meantime check at CircleCI config.
> 
> https://github.com/cosmos/ledger-cosmos/blob/8c389e18c92ba9bd6ad41780a938f07b0234e8fd/.circleci/config.yml#L12
> 
> If you run something like `cmake -DDISABLE_DOCKER_BUILDS=ON . && make` it will compile local code but it will not try to crosscompile the apps. Typically this is more efficient too.

**Comment by saadbutt** [comment]
cmake -DDISABLE_DOCKER_BUILDS=ON . && make  Working on local for Now. Thanks

**Comment by jleni** [comment]
any reason why this ticket got reopened?
