### ISSUE TITLE
Error Upload the app to the device

### ISSUE THREAD

**Issue by RNS135** [cosmos/ledger-cosmos-obsolete#156]
Unable to run this command after following all steps:
"make load_cosmos          # Loads Cosmos app       (for users)"
Output of this command is:
make: *** No rule to make target 'load_cosmos'.  Stop.

Please help.

**Comment by saadbutt** [comment]
We are facing a same issue after cmake -DDISABLE_DOCKER_BUILDS=ON . && make. 
@jleni is there any other way to upload app to the device?

**Comment by jleni** [comment]
There are actually two independent compilations...

Use cmake to run unit tests and develop on your host computer. That way it is possible to improve the decoder and other components without wasting time with the device.

Use make to build inside docker, etc. @RNS135 I think you are using the "internal" make file inside `src/ledger`. You should not use that. Instead run the `Makefile` in the root directory. That one launches a docker container with everything preinstalled when you use `make build_cosmos` and then you can use `make load_cosmos`

I hope this is clear enough. Feel free to send me more questions.

**Comment by jleni** [comment]
@RNS135 @saadbutt if you found that this could solve your problems. 

It would be great (if you have 5 minutes) if you could send a PR with some quick changes to the docs so other people in the future do not get confused about these differences.

**Comment by RNS135** [comment]
Sure @jleni, thanks

**Comment by jleni** [comment]
Is it now working? Should I close this issue then?
