### ISSUE TITLE
Cannot sign in with Ledger devices in win10 may 2019 update + chrome

### ISSUE THREAD

**Issue by jleni** [cosmos/ledger-cosmos-obsolete#157]
Copying over https://github.com/luniehq/lunie/issues/2754 opened by @williamchong007 to simplify tracking.

> **Describe the bug**
> I am using ledger nano S to sign in on windows 10 may 2019 update (version 1903 build 18362.175). After clicking sign in with ledger, `Windows Security` popup (the new native FIDO U2F from Microsoft i suppose) keep on popup up and automatically closing itself for a while.
> After the popup flashing stops and I accepted login on ledger, I got stuck with an error screen in the windows security popup. Closing the window and retrying sign in yields either another error popup or getting stuck with `Take action on your security key` , while ledger is stuck in `Returning Address...`
> 
> **To Reproduce**
> 
> 1. Go to lunie and try sign in with ledger. Click the signin button with ledger connected and cosmo app open.
> 2. Get a lot of "Windows security" popup on and off flashing the screen. Wait until it stop and a prompt appears on ledger.
> 3. Click accept button on ledger.
> 4. See an error screen in the Windows Security popup. Ledger stuck in `Returning Address`.
> 
> **Expected behavior**
> Only 1 popup of Windows security asking me to press button should appear, I should be about to login after I press accept on ledger.
> 
> **Screenshots**
> After the "Windows Security" popup flashing decided to stop
> ![1](https://user-images.githubusercontent.com/6198816/59967601-f7e5ae80-955e-11e9-8572-9d13cbfe8f1b.PNG)
> After pressing accept on ledger:
> ![image](https://user-images.githubusercontent.com/6198816/59967522-af79c100-955d-11e9-89bb-253bd6db3e70.png)
> Result:
> ![3](https://user-images.githubusercontent.com/6198816/59967602-f9af7200-955e-11e9-9fc0-0c0f33b52517.PNG)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10  (version 1903 build 18362.175)
> * Browser: Chrome
> * Version: 75.0.3770.100

The issue has been reproduced and affects browsers running Windows 10 v1903 (and upwards). The `U2F` transport has been affected by this upgrade.

`HID` and `WebUSB` transports are not affected.
Unfortunately, Windows 10 does not support WebUSB (unless drivers are manually installed).

*Current workarounds / alternatives*
- Use a host running `Linux` or `MacOS`
- Use the Cosmos CLI (any OS)
- Use a desktop wallet (only web browsers in Windows are affected)

**Comment by jleni** [comment]
The latest recommendation with respect to this issue is to use:
- WebHID in Windows 10 (enabling Chrome v78+ WebHID support)
- WebUSB in Linux / MacOS

**Comment by jleni** [comment]
@faboweb Now that Lunie has upgraded to WebHID in Windows. 
I think we can close this issue, agree?

**Comment by faboweb** [comment]
Yes finally!!

**Comment by wordkeepa** [comment]
How to enable WebHID in Chrome?

**Comment by faboweb** [comment]
Copy this URL into your address bar: chrome://flags/#enable-experimental-web-platform-features

**Comment by wordkeepa** [comment]
Thank you!
