### ISSUE TITLE
[Firmware] After upgrade to ledger 1.6 can not open the app from the custom build

### ISSUE THREAD

**Issue by yun-yeo** [cosmos/ledger-cosmos-obsolete#159]
After upgrade to ledger firmware 1.6, the ledger is stuck in "Open application" screen for the custom build and load. It may be the problem of ledger firmware at handling Non genuine app

**Comment by jleni** [comment]
Have you upgraded to Cosmos app version > v2.x.x. Support for SDK 1.6 is already there.
https://github.com/LedgerHQ/ledger-app-cosmos/pull/10

Actually, we are already at v2.2 which is know to work well with firmware 1.6

**Comment by jleni** [comment]
@YunSuk-Yeo I will close for now. Please reopen and let me know if the suggestion didn't fix your problem.
