### ISSUE TITLE
What is "index" and "account" in the cosmos ledger app?

### ISSUE THREAD

**Issue by shunjizhan** [cosmos/ledger-cosmos-obsolete#163]
I am a little bit confused about the addresses in the app, can someone help me?

When I open the cosmos app on ledger, there is a "show address" option that has a lot of addresses. However, when I use the Lunie wallet it seems to always connect to the address associated with "Account 0 and Index 0". Is the only actual address that is generated from the ledger 24-word mnemonic phrase? And what are the other addresses for? Thanks!

**Comment by jleni** [comment]
Lunie decides to query a single address with that specific path `44'/118'/0'/0/0` 

The app/device can derive any path that starts with 44'/118'/....  so you actually have an almost unlimited amount of addresses in the device. It is just a matter of the applications that you are using to access them. For example, the CLI can access most of them.

**Comment by jleni** [comment]
I am closing this because it is not an issue but feel free to answer after that.

**Comment by shunjizhan** [comment]
Thanks for the answer, that makes things much clear! 

I have a follow up question: for bitcoin or other coins, a 24-word mnemonic phrase => a private key => a single address saved in ledger nano s. So how can cosmos have so many address based on one private key? Thanks a for your help : )
