### ISSUE TITLE
Why is it obsolete?

### ISSUE THREAD

**Issue by shunjizhan** [cosmos/ledger-cosmos-obsolete#166]
Is it still safe to use? Should I withdraw all atom from ledger nano wallet that use this app? Thanks!

**Comment by jleni** [comment]
No, only the repository is obsolete. Do not worry. We have unified all code + tests in a single place:
https://github.com/cosmos/ledger-cosmos

The published app is fine and continuously maintained.

**Comment by shunjizhan** [comment]
Thanks for the clarification!
