### ISSUE TITLE
Json validation

### ISSUE THREAD

**Issue by brejski** [cosmos/ledger-cosmos-obsolete#52]
According to the json parsing specification (from TXSPEC.md):

The Ledger device MUST validate that supplied JSON is valid. Our JSON specification is a subset of [RFC 7159](https://tools.ietf.org/html/rfc7159) - invalid RFC 7159 JSON is invalid Ledger JSON, but not all valid RFC 7159 JSON is valid Ledger JSON.

We add the following two rules:
- No spaces or newlines can be included, other than escaped in strings
- All dictionaries must be serialized in lexicographical key order

Currently only basic validation is implemented based on the jsmn library. We either need to update jsmn or add extra validation layer in the app along with negative tests that demonstrate malformed messages.

**Comment by jleni** [comment]
Consolidating issue https://github.com/cosmos/ledger-cosmos/issues/40 here

**Comment by jleni** [comment]
Linking to PR https://github.com/cosmos/ledger-cosmos/pull/77

**Comment by jleni** [comment]
Linking to PR https://github.com/cosmos/ledger-cosmos/pull/79

**Comment by jleni** [comment]
I guess that after #81 #80 we can close this ticket?
@brejski @cwgoes

**Comment by cwgoes** [comment]
Yes; I think we can close this.

**Comment by brejski** [comment]
Yes
