### ISSUE TITLE
Better comments and documentation

### ISSUE THREAD

**Issue by brejski** [cosmos/ledger-cosmos-obsolete#54]
Add comments. Every public APIs should have comment describing function purpose, its arguments and return values. 
Add documentation. Every major component: view, parser, signing, goclient should come with a paragraph explaining the high level architecture.

**Comment by jleni** [comment]
Some definitions:
- LLVM style with 4 space indent
- DOxygen style comments (initial, improvements might be necessary)

The following PR aligns the code to those guidelines https://github.com/cosmos/ledger-cosmos/pull/75
