### ISSUE TITLE
Break down json_parser.h/cpp 

### ISSUE THREAD

**Issue by brejski** [cosmos/ledger-cosmos-obsolete#55]
json_parser grew out of control to become a one big monster with tons of API representing different level of granularity (low level generic json parsing to very specific cosmos message parsing APIs).

We should move some of the higher level APIs to a new file.

**Comment by jleni** [comment]
is this still relevant?

**Comment by brejski** [comment]
Yes, it's part of the cleanup. json_parser contains transaction parsing code which should really be moved to another file.

**Comment by brejski** [comment]
Issue has been fixed now.
