### ISSUE TITLE
Define and consolidate coding style

### ISSUE THREAD

**Issue by brejski** [cosmos/ledger-cosmos-obsolete#56]
We are using bunch of various coding styles (function names, variable names, tabs/spaces, curlies on new lines etc.). We should agree on a single style, ideally something that we can auto-format and consolidate all the code.

**Comment by jleni** [comment]
Some definitions:
- LLVM style with 4 space indent
- DOxygen style comments (initial, improvements might be necessary)

The following PR aligns the code to those guidelines https://github.com/cosmos/ledger-cosmos/pull/75
