### ISSUE TITLE
SDK dependencies

### ISSUE THREAD

**Issue by jleni** [cosmos/ledger-cosmos-obsolete#73]
Some of the go tests are still using the ledger-integration branch

https://github.com/cosmos/ledger-cosmos/blob/2e43e31e44557a7a9ba78a4d6c5be8492bb05e50/src/goclient/Gopkg.toml#L30

Some guidance is needed to update/accommodate new dependencies

**Comment by cwgoes** [comment]
That should no longer be necessary as that branch has been merged. I'll write a PR to update the dependency tomorrow.

**Comment by brejski** [comment]
Hey Chris, goclient.go is still using (branch cwgoes/ledger-integration  da66010), which is based on sequences (as an array). This is currently failing json validation. Should we update this dependency to master or any other branch?
