### ISSUE TITLE
Python Install Instructions

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/ledger-cosmos-obsolete#78]
I was testing out the ledger app today and its great! Thank you @brejski and @jleni! Trying the install from scratch instructions I ran into some issues however. I was able to get everything built in `docker` with no issues, however when I tried to

```bash
$ ./nanocli.sh delete
OR
$ ./nanocli.sh load
``` 
I ran into errors using `python2.7`. I was able to fix this by running `python3.7`, using a `virtualenv` and `pip install ledgerblue`. This directly contradicts the instructions here and prevented me from loading/unloading. It should just be a small change to the `README`, and otherwise everything else works great!

cc @cwgoes

**Comment by cwgoes** [comment]
Were you able to load/unload the application with python3.7?

**Comment by jackzampolin** [comment]
@cwgoes Yup! No issues there. Had to `pip install` a couple of things but it worked.

**Comment by cwgoes** [comment]
> @cwgoes Yup! No issues there. Had to pip install a couple of things but it worked.

Great - do you want to write a PR for the README with the changes you needed to make?
